### ISSUE TITLE
Add build warnings

### ISSUE THREAD

**Issue by theofidry** [humbug/box#123]
Because of some incompatible settings, one setting may be ignored. For example requirements checker cannot be used without `stub` to `true`. However I think that bailing out would be a bad UX, instead a warning could be displayed

**Comment by keradus** [comment]
warning is nice, i would even crash and ask user to fix the config and decide what he want explicitly, instead of deciding for him (assuming that stub is used no main omitted or stub is default and main included)

**Comment by keradus** [comment]
wow, looks nice and big. thanks for your work on that, @theofidry !
it's a pity noone had a chance to review that ;)

**Comment by theofidry** [comment]
Haha sorry! I'm really used to not have much people willing to review my projects, at least for PHP-Scoper & Box.

That said it can still be reviewed, I'm more than happy to address the raised comments in a separate PR.

There is probably gonna be 2 other PRs regarding this feature as well very soon (hopefully), I'll ping you on those if you wish :)

**Comment by keradus** [comment]
I can understand your approach ;)
usually, with review process, is way slower than just "Works? works! merge.", yet can provide some values
