### ISSUE TITLE
[Suggestion] Switch from makefile to Robofile

### ISSUE THREAD

**Issue by c33s** [humbug/box#145]
just an idea, please just close if you think the switch is not worth the effort.

beeing in the php world and using it on multiple platforms (linux, windows & mac) i personally prefer to stay in the php world if this is possible and a good choice.

my suggestion would be to switch away from the makefile to a robofile https://robo.li/ it is able to do the same thing. developers don't have to "learn" another syntax (yes i know it is not that difficult) and also have the power of php at hand.

**Comment by theofidry** [comment]
Hi, thanks for the suggestion!

There is a few reasons for it:

- `Make` is available everywhere. So with it I can really achieve the git clone + make and everything just works experience
- Being able to stay in the PHP world sure is tempting, but besides the usage of Makefile being very basic (I'm far from being an expert at it)
- The user is not really expected to modify it. If one is unfamiliar with it and don't know how to change it, it's not an issue I can easily help with that.
- The main usage should remain doing `make`, seeing the available commands and then just doing `make cmd`

So for all of those reasons, I don't think the switch is worth the effort. It is a cool project so I'll keep track of it
