### ISSUE TITLE
PHAR minimal requirements

### ISSUE THREAD

**Issue by theofidry** [humbug/box#164]
The extension `ext-phar` will always be necessary for the PHAR and as such should be included in the requirements whether or not it is declared in the `composer.json` `require` section.

If the PHAR is compressed, the `zip` extension is also required, but it is likely that PHP will not be able to even execute it without it anyway so to be check if it's worth it or not

**Comment by c33s** [comment]
just a thought: isn't it also possible to keep the files uncompressed? so zip would be optional. not sure if an uncompressed phar can be executed without the zip extension

**Comment by theofidry** [comment]
Yes, this is why Composer does not compress theirs
