### ISSUE TITLE
Add warning when dev dependencies are found

### ISSUE THREAD

**Issue by theofidry** [humbug/box#18]
Idea got thanks to @jakzal: when a PHAR is being build with Box and a dev dependency is found, a warning should be given to the user. Indeed there is zero benefit to include them and on the contrary it's more dangerous than anything. Just to give a few reasons:

- They are useless
- It increases the PHAR size
- This _may_ have a performance impact when running the PHAR
- It has a performance impact on the building time (as they are more files...)
- You potentially open a vector of attack as dev dependencies are not always built with security in mind (and neither should they be: they are meant for dev not production)

**Comment by kelunik** [comment]
Just exclude all of those during generation? https://github.com/MacFJA/PharBuilder does that successfully, but keeps files in `"autoload": { "files": [...] }`, so it doesn't have to modify the autoloader.

**Comment by theofidry** [comment]
Yes [I saw that](https://github.com/MacFJA/PharBuilder/blob/master/app/PharBuilder.php#L433-L465) and was thinking of something similar.

I'm still now entirely sure how to apply though. Unlike in PharBuilder you declare your own finders. Maybe making use of the blacklist?

Also reading the `composer.json` file is not a trivial decision either as it implies to know where the `composer.json` file is. But I think that can be ok as we'll kind of need that anyway for PHP-Scoper as after scoping the files it is required to dump the autoloader again.

**Comment by theofidry** [comment]
Another thing to note is that there is a lot more possible locations for tests, for example codeception, phpspec or behat tests are not under `tests`.
