### ISSUE TITLE
Allow to disable the main script

### ISSUE THREAD

**Issue by theofidry** [humbug/box#206]
When using your own stub, e.g. in PsySH, the main script _may_ be unnecessary

**Comment by keradus** [comment]
what is "main script" ?

**Comment by theofidry** [comment]
Your application entry point which is the [main setting](https://github.com/humbug/box/blob/master/doc/configuration.md#main-main).

The PHAR has another entry point which is the stub, which usually call the main script. But since in some cases the main script is registered as the stub, it doesn't make sense to include the main script in this case (although it has no effect, it's is only for a minor weight improvement)

**Comment by keradus** [comment]
so, if there is `stub` pointing to concrete file, `main` shall need to be empty, right?

**Comment by theofidry** [comment]
yes or completely omitted.

There is a few cases where there is contradicting configurations ever since box2, I think it would be nice to provide some warnings about it to the user (see https://github.com/humbug/box/issues/123) but allowing the user to carry on

**Comment by keradus** [comment]
warning is nice, i would even crash and ask user to fix the config and decide what he want explicitly, instead of deciding for him (assuming that stub is used no main omitted or stub is default and main included)

**Comment by theofidry** [comment]
I'm hesitating a bit between the two. Sometimes you want to tweak a bit the config to just test one setting and in those cases it's annoying to have to change more than one thing. For example you want to disable the signature for some reasons I don't feel like you should need to remove the private key path as well.

Since those decisions have always been made, it may be better to stay in line and just provide feedback of some kind about the config rather than bailing out hard. Another point is that it would make the Box2 -> Box3 migration easier
