### ISSUE TITLE
Alpha 6 phar is erroring

### ISSUE THREAD

**Issue by jwage** [humbug/box#243]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.0.0-alpha.6
| PHP version | 7.1.10
| Platform with version | CentOS
| Github Repo | https://github.com/doctrine/migrations

When I run `php box.phar` I get the following:

```
$ php box.phar
PHP Fatal error:  Uncaught PharException: cannot load phar "/data/doctrine/migrations/box.phar" with implicit alias "4cd4c5c97c4a42d553c561ab044d0426.phar" under different alias "box-auto-generated-alias-5b08872a5737b.phar" in /data/doctrine/migrations/box.phar:14
Stack trace:
#0 /data/doctrine/migrations/box.phar(14): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /data/doctrine/migrations/box.phar on line 14
```

It works with Alpha 5.

**Comment by theofidry** [comment]
Closed by https://github.com/humbug/box/releases/tag/3.0.0-alpha.7 :)
