### ISSUE TITLE
Undefined variable when using GZ compression on Windows

### ISSUE THREAD

**Issue by lookyman** [humbug/box#261]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.0.0-beta.3@37699fe
| PHP version | 7.2.2
| Platform with version | Win 10
| Github Repo | -

The problem seems to be [here](https://github.com/humbug/box/blob/37699fe4fa12cffc52fb92afe5377bde2ed96f8d/src/Console/Command/Compile.php#L643). If the `if` statement above evaluates to `false`, the variables `$softLimit` and `$hardLimit` are never defined and cannot be used in the anonymous function's `use`.

<details>
 <summary>box.json.dist</summary>
 
 ```json
 {
  "banner": false,
  "base-path": "../tmp/build",
  "check-requirements": false,
  "compactors": [
    "KevinGH\\Box\\Compactor\\Php",
    "KevinGH\\Box\\Compactor\\PhpScoper"
  ],
  "compression": "GZ",
  "directories": [
    "conf",
    "src",
    "vendor"
  ],
  "output": "../phpstan.phar",
  "php-scoper": "../../build/scoper.inc.php"
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ php box.phar compile
 > Box version 3.0.0-beta.3@37699fe 2018-06-14 10:50:22


 // Loading the configuration file "C:\server\www\phpstan\phpstan-compiler\build\box.json".

Building the PHAR "C:/server/www/phpstan/phpstan-compiler/tmp/phpstan.phar"
? Registering compactors
  + KevinGH\Box\Compactor\Php
  + KevinGH\Box\Compactor\PhpScoper
? Adding main file: C:/server/www/phpstan/phpstan-compiler/tmp/build/bin/phpstan
? Skip requirements checker
? Adding binary files
    > No file found
? Adding files
    > 821 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
? Dumping the Composer autoloader
? Removing the Composer dump artefacts
? Compressing with the algorithm "GZ"

In Compile.php line 330:

  Undefined variable: softLimit
 ```
</details>

**Comment by theofidry** [comment]
Indeed that doesn't look right. Thanks for the report! Could you give a try to #262?

**Comment by lookyman** [comment]
Yep, it works. Thanks!

**Comment by theofidry** [comment]
Cool.

There is probably more Windows related issues, c.f. #193.
