### ISSUE TITLE
Refactor the PHP annotation based compactor

### ISSUE THREAD

**Issue by filips123** [humbug/box#263]
| Question    | Answer
| ------------| ---------------
| Box version | 3.0.0-beta.4
| PHP version | 7.2.6
| Platform with version | Ubuntu 16.04
| Installation type | Composer

Some Composer dependencies (`herrera-io/annotations`) are abandoned. You should use some alternatives.

```
Package herrera-io/annotations is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by theofidry** [comment]
Indeed, PRs to remove this dependency are welcomed! This dependency is only used for the [`Php` compactor](https://github.com/humbug/box/blob/5ed8f0f/src/Compactor/Php.php) which is tested by [this test](https://github.com/humbug/box/blob/5ed8f0f/tests/Compactor/PhpTest.php). I'm also fine to change some behaviours if necessary/easier as long as it makes sense

**Comment by filips123** [comment]
So it is OK to just remove dependency, file and test?

**Comment by theofidry** [comment]
well I suppose this dependency is currently used. But yes we can remove it if it is not necessary, use a different one or find a way to do without a dependency at all

**Comment by filips123** [comment]
Could you please remove this dependency or use alternative?

**Comment by theofidry** [comment]
It’s planned, but I have little time and little interest in it right now.
It works for now (and has been for 3 years). So while I don’t like having a
deprecated dependency and think some stuff could be improved, I just hope
someone would be ready to help for it as I neither have the time or energy
to do everything by my own :)
