### ISSUE TITLE
Add support for multiple output PHARs

### ISSUE THREAD

**Issue by filips123** [humbug/box#265]
Add support for multiple output PHARs with same configuration and content. Also add support for different PHARs in one config file.

**Comment by theofidry** [comment]
Could you expend on what would be the use case?

**Comment by theofidry** [comment]
What is the goal though? Because I have hard time what result you are expecting for the first one and for the second I think having multiple configuration files would be clearer

**Comment by filips123** [comment]
How to use multiple configuration files?

**Comment by theofidry** [comment]
With the `config` option: `box compile -config=myfile`, you can see all the options with the `--help`  option

**Comment by filips123** [comment]
Thank you!
