### ISSUE TITLE
Creating a phar without the '.phar' extension 

### ISSUE THREAD

**Issue by MaryCoding** [humbug/box#272]
Glad this project is being maintained with greater features now. I just transitioned to the latest version from 2.7. I was wondering if its possible to create a phar file without the extension? Thanks

**Comment by theofidry** [comment]
Hello,

As answered on the Slack (but in case someone comes across this issue), I do not know if it's possible. I did not dig much into it to see if it's feasible so one might want to check, but I would personally recommend against using the PHAR built-in signature in the first place. I hope to find some time to update the docs regarding this point soon enough.
