### ISSUE TITLE
Busybox-like invocation routing support

### ISSUE THREAD

**Issue by dkarlovi** [humbug/box#273]
## Feature Request

Some tools have multiple executables (example, CodeSniffer has sniffer and fixer, same for Psalm). They could provide a separate PHAR for each tool.

But, they might also package their tools into a single, project-level PHAR. The invocation routing would then be determined by `argv[0]`, [the same way Busybox does](https://busybox.net/FAQ.html#getting_started):

Example:

```
$ wget psalm.phar

$ ln -s psalm.phar psalm
$ ln -s psalm.phar psalter

$ ./psalm   # runs Psalm
$ ./psalter # runs Psalter
```

Running just the PHAR would run the "default" binary, but would need some way of discovery what's inside.

**Comment by theofidry** [comment]
I'm not sure there is much to do on Box side. If you forget about the PHAR for a moment and just consider your application CLI, you have the exact same issue: do you have a single CLI entry point which supports several commands or one entry point per command? For the format, nothing to do from Box PoV, for the second, you would likely end up with one PHAR per entry point

**Comment by dkarlovi** [comment]
Box could generate a shim like this:

```php
switch ($argv[0]) {
    case 'psalter':
        // fix env and run vendor/bin/psalter
    break;
    default:
    case 'psalm':
        // fix env and run vendor/bin/psalm
}
```

Wouldn't that work?

**Comment by theofidry** [comment]
I'll be closing this one as, at least for now, I feel this is a problem that should be fixed at the application and moving it Box would only over-complicate things.
