### ISSUE TITLE
Add Homebrew installer

### ISSUE THREAD

**Issue by pierredup** [humbug/box#275]
## Feature Request

Adding a [homebrew](https://brew.sh/) formula would make it much simpler to install Box on MacOS. It would also help with keeping your local version up to date without any manual work (I often just run `brew upgrade` to upgrade all my packages).

### What is required?

The formula needs to be in a separate repository (E.G humbug/homebrew-box) and contain a formula definition file. If you create the repository, I'll create a PR with the necessary files

### Using brew to install box

Once the formula is added, then installing box would be as simple as

```bash
$ brew tap humbug/box
$ brew install box
```

Upgrading box to a newer version:

```bash
$ brew upgrade box
```

### Keeping the formula up to date

Using the [tap-release](https://github.com/apps/tap-release) Github app, you can automatically publish an update to the formula each time a release is created. This means there is no extra maintenance to keep the formula up to date (I will also create a PR adding the config for the tap-release bot)

**Comment by theofidry** [comment]
Great idea :)

I've created the repository https://github.com/humbug/homebrew-box, I can't promise to look at it immediately though

**Comment by theofidry** [comment]
Thanks for https://github.com/humbug/homebrew-box/pull/1, I'll try to have a look at that tap-release app ASAP
