### ISSUE TITLE
how to Include dev package files easily

### ISSUE THREAD

**Issue by llaville** [humbug/box#300]
Hello Théo,

I've just begun to play with Box 3 on my project https://github.com/llaville/php-compatinfo-db 
I  was disappointed when I read at https://github.com/humbug/box/blob/master/doc/configuration.md#including-files  this line. 
  
> Note: By default, dev dependencies are excluded for both strategies

Could you provide an example of json configuration that will be able to add easy one or all of dev packages dependencies easily. 
It will help I think lot of people and allow to more adoption in the community !

Thanks in advance 
Laurent

**Comment by theofidry** [comment]
A way to do it is to not rely on the auto-discovery, so you can include your packages as follows:

```
{
  "directories": ["src", "tests"]
}
```

I however have a bit of trouble to understand why you would want to include your dev packages in your PHAR.

**Comment by llaville** [comment]
In case of my project (see [composer.json](https://github.com/llaville/php-compatinfo-db/blob/1.x/composer.json)) `symfony/console` is not mandatory because goal of this project is to provide a SQLite database.  CLI command is only an alternative.  But in case of a PHAR distribution, i've choosen to provide the `data/handleDB.php` (that provide a symfony console app) as entrypoint.

**Comment by theofidry** [comment]
That's a different issue IMO. What you seem to be describing is you have different dependencies depending of distribution. Maybe you should consider adding that dependency for your PHAR (but only the PHAR, not your library).

One example is [psysh](https://github.com/bobthecow/psysh/blob/master/Makefile) which provides several PHARs depending of the PHP target and to have some which includes polyfills (but are heavier) but without (lighter)

**Comment by theofidry** [comment]
Does that answer your question @llaville?

**Comment by llaville** [comment]
@theofidry Sorry to reply with late.

No that answer is not what i'm expected to get. But now I've tried to do it the old-fashioned way (like I did with Box2). And results are not as expected.

First with my project https://github.com/llaville/php-compatinfo-db on master branch.

And this `box.json` config file

```
{
    "directories": ["src"],
    "files": [
        "data/handleDB.php",
        "data/ReferenceCollection.php",
        "data/compatinfo.sqlite",
        "LICENSE",
        "vendor/autoload.php"
    ],
    "finder": [
        {
            "name": "*.php",
            "in": "vendor/composer"
        },
        {
            "name": "*.php",
            "notPath": "/Tests/",
            "in": "vendor/symfony"
        },
        {
            "name": "*.php",
            "in": "vendor/psr/log/Psr"
        },
        {
            "name": "*.php",
            "in": "vendor/monolog/monolog/src"
        }
    ],
    "git-version": "package_version",
    "main": "data/handleDB.php",
    "output": "phpcompatinfodb.phar"
}
```
I've compiled the phar version with command  `box.phar compile`

Version used is  `Box version 3.1.2@f5403bd 2018-10-16 10:34:07 UTC`

When I've inspect content with command `box.phar info --list phpcompatinfodb.phar`, I see this result : 
```
API Version: 1.1.0

Archive Compression: None

Signature: SHA-1
Signature Hash: 21BC11D5D333BA0ED4C2E0C298E55105D1B2A0D9

Metadata: None

Contents: 55 files (1.68MB)
.box/
  .requirements.php [NONE] - 2.21KB
  bin/
    check-requirements.php [NONE] - 414.00B
  composer.json [NONE] - 591.00B
  composer.lock [NONE] - 52.84KB
  src/
    Checker.php [NONE] - 4.93KB
    IO.php [NONE] - 4.18KB
    IsExtensionFulfilled.php [NONE] - 476.00B
    IsFulfilled.php [NONE] - 170.00B
    IsPhpVersionFulfilled.php [NONE] - 657.00B
    Printer.php [NONE] - 3.64KB
    Requirement.php [NONE] - 1.05KB
    RequirementCollection.php [NONE] - 1.64KB
    Terminal.php [NONE] - 3.11KB
  vendor/
    autoload.php [NONE] - 438.00B
    composer/
      ClassLoader.php [NONE] - 13.11KB
      LICENSE [NONE] - 1.04KB
      autoload_classmap.php [NONE] - 2.17KB
      autoload_namespaces.php [NONE] - 149.00B
      autoload_psr4.php [NONE] - 328.00B
      autoload_real.php [NONE] - 1.42KB
      autoload_static.php [NONE] - 3.44KB
      installed.json [NONE] - 31.13KB
      semver/
        LICENSE [NONE] - 1.03KB
        src/
          Comparator.php [NONE] - 1.56KB
          Constraint/
            AbstractConstraint.php [NONE] - 1.02KB
            Constraint.php [NONE] - 4.21KB
            ConstraintInterface.php [NONE] - 379.00B
            EmptyConstraint.php [NONE] - 833.00B
            MultiConstraint.php [NONE] - 2.05KB
          Semver.php [NONE] - 2.54KB
          VersionParser.php [NONE] - 15.30KB
LICENSE [NONE] - 1.46KB
data/
  ReferenceCollection.php [NONE] - 17.61KB
  compatinfo.sqlite [NONE] - 1.36MB
  handleDB.php [NONE] - 70.35KB
src/
  Bartlett/
    CompatInfoDb/
      Environment.php [NONE] - 3.13KB
      ExtensionFactory.php [NONE] - 7.41KB
      ReferenceInterface.php [NONE] - 2.33KB
      SqliteStorage.php [NONE] - 7.86KB
vendor/
  autoload.php [NONE] - 178.00B
  composer/
    ClassLoader.php [NONE] - 13.11KB
    LICENSE [NONE] - 1.04KB
    autoload_classmap.php [NONE] - 583.00B
    autoload_namespaces.php [NONE] - 149.00B
    autoload_psr4.php [NONE] - 225.00B
    autoload_real.php [NONE] - 1.42KB
    autoload_static.php [NONE] - 1.46KB
    semver/
      src/
        Comparator.php [NONE] - 2.50KB
        Constraint/
          AbstractConstraint.php [NONE] - 1.58KB
          Constraint.php [NONE] - 5.83KB
          ConstraintInterface.php [NONE] - 606.00B
          EmptyConstraint.php [NONE] - 1.05KB
          MultiConstraint.php [NONE] - 2.54KB
        Semver.php [NONE] - 3.13KB
        VersionParser.php [NONE] - 19.31K
```
Only composer files in finder section were added, while I'm expected to have also Symfony Components, Psr and Monolog source code.
There are present and well installed.

What did I missed ?

**Comment by theofidry** [comment]
I'll try to check it out ASAP

**Comment by theofidry** [comment]
Hm indeed you cannot: Box attempts to remove dev dependencies whenever possible. It's a bit annoying but there is way more cases where you want to remove them than not so IMO the possible solutions:

- Don't be picky about the files included in your PHAR (it's not that big anyway and you can always compress it), here is a working configuration:

<details>
<summary>box.json.dist</summary>
```json
{
    "directories": ["src", "vendor"],
    "files-bin": [
        "LICENSE"
    ],
    "finder": [
        {
            "in": "data",
            "exclude": "references"
        }
    ],
    "dump-autoload": false,
    "git-version": "package_version",
    "main": "data/handleDB.php",
    "output": "phpcompatinfodb.phar"
}
```
</details>

Note a couple of things with it:

  - unlike `finder` dev dependencies are not removed from `directories`
  - the `main` would not be necessary if you register the `bin` in your `composer.json`
  - `"dump-autoload": false,` is necessary because you are including dev dependencies but Box tries to dump an optimized autoloader (and without dev deps)

- It could also be possible to add a new config option to not mind the dev dependencies, but I honestly think it's a bit far-fetched and would rather go with the solution °3

- https://github.com/humbug/box/issues/300#issuecomment-428701354 which IMO is a way cleaner and intuitive solution: your `symfony/console` should, for the PHAR, not be a dev dependencies, it's a core dependency. The problem you are encountering is that you have a difference of dependencies between your library and your shipped application. So for it the best way is either have a dedicated `composer.json` for the application (eventually with its `composer.lock`) or a script dynamically including it for when building the PHAR.

**Comment by theofidry** [comment]
I think this answers the question, if you need more info please ping me on Slack :)
