### ISSUE TITLE
Missing phar file at releases page @ v3.3.0's assets

### ISSUE THREAD

**Issue by KEINOS** [humbug/box#326]
It seems that the compiled "box.phar" v3.3.0 at the releases page is missing.

I would be grateful if it is provided as an official compiled "box.phar" like the earlier versions.

<kbd>![releases humbug box_600x](https://user-images.githubusercontent.com/11840938/48382973-182ad080-e727-11e8-9e34-1e1b3b7c77a1.png)</kbd>

And thank you for your tremendous effort in keeping the BOX alive.

**Comment by theofidry** [comment]
Damn indeed I went too fast with the release there was an error in the CI. I've released [3.3.1](https://github.com/humbug/box/releases/tag/3.3.1) which should solve the issue

**Comment by KEINOS** [comment]
@theofidry 

Thanks for the quick response!

Though, it seems that you still forgot to attach the compiled phar... 😭

https://github.com/humbug/box/releases/tag/3.3.1

You need a ☕️ break!

**Comment by theofidry** [comment]
It's just the CI being a bit slow :) It will be uploaded automatically once https://travis-ci.org/humbug/box/jobs/454378135 is finished
