### ISSUE TITLE
Phar's composer not always configured as expected

### ISSUE THREAD

**Issue by feamsr00** [humbug/box#333]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.1.1 
| PHP version | 7.2.10 
| Platform with version | Win10 v1803

A simple composer.json with requires *is* present.
The phar application requires vendors\autoload.php

### Observations

 Auto-discover files on. Valid autoloading.
 Auto-discover files is off (`directories` et al. is present. e.g. `	"directories": ["src"]`). Misconfigured autoloading. *However .\vendors is present in the phar*
 Auto-discover files is off. `directories` includes 'vendors'. _Valid autoloading_.

I'm not sure how to take this further. Is this a bug or expected but undocumented behavior? Is there a scenario in which vendor is included even with AD off but it's _not_ supposed to wok conventionally?

**Comment by theofidry** [comment]
>The phar application requires vendors\autoload.php

Hm that shouldn't happen.

>Auto-discover files is off (directories et al. is present. e.g. "directories": ["src"]). Misconfigured autoloading. However .\vendors is present in the phar

I'm not sure to understand that one.

Rather than `vendor/autoload.php`, if you have a `composer.lock` what is important is `vendor/composer/installed.json`. A `composer.lock` indicates you have dependencies (you could use Composer but with no dependency in which case you will not have a `.lock`), but what Box is doing is a `dump-autoload` not `install`, and dependencies are installed correctly only if there is a `vendor/composer/installed.json` (which is necessary to dump the autoload)

**Comment by feamsr00** [comment]
I initially observed this with a `finder` directive that was just looking for ".php" and started to wonder if that was the case (it skipping `installed.json`). However, once the directive was removed, I still observed the behavior (hence the report). I'm curious, is there any part of box that will examine your composer install and "box" it no matter what? If so, should it? If not, then the issue is maybe a red-herring as the presence of the vendors folder is misleading.

However, if Box should examine your projects composer setup, and if it should "box" the vendors no matter what (given that auto discovery was off: not set in config and reported off in output), then what's causing the `installed.json` to go missing without explicit inclusion?

Bear with me as I'm inferring a lot of about the "intentionality" of this functionality.

(Note: By "application requires" I do mean the project to be boxed has code to do req' autoload.php. That's not in conflict, right?)

**Comment by theofidry** [comment]
I've double check the documentation and it is correct.

>If a composer.lock file is found as well, the file vendor/composer/installed.json will be required too.

By this, I mean that without the `installed.json` file, dumping the autoloader will result in an invalid classmap. If Box is taking care of the auto-discovery, then it is included but automatically but if you have the auto-discovery off you need to include it.

I've implemented #337 which should help to stop those scenarios
