### ISSUE TITLE
Probably my misunderstanding how to include files in a phar

### ISSUE THREAD

**Issue by clevelas** [humbug/box#349]
I'm struggling building my project.  My box.json looks like this:

{
    "main": "bin/appbin.php"
}

In that bin/appbin.php is a require line:
require 'config.php'

That config.php file exists in the bin directory.  But when I build the project with 'box build', it is not included in the phar.  'box info appbin.phar -l' doesn't show it.

Why is not being included?  Is there a better way to do it?

**Comment by theofidry** [comment]
There is some documentation regarding this [here](https://github.com/humbug/box/blob/master/doc/configuration.md#including-files), but I admit I'm quite familiar with PHARs now so it's easy for me to miss what can be confusing for someone not familiar with PHARs. So I'll try to explain it differently and feel free to do a PR with a suggestion if you think the documentation can be improved in that regard!

By default, i.e. without any configuration file, Box tries to:

- Find the entry point of your application (cf. [the `main` setting](https://github.com/humbug/box/blob/master/doc/configuration.md#main-main)) which by default is the `bin` setting of your `composer.json`
- Include your project files via the information inferred by your `composer.json` (and under the hood it is actually combined with the `composer.lock`  and `vendor/composer/installed.json`). This is done by checking the different `autoload` entries in the above JSON files.

So what is likely happening is that your `config.php` file is for some reason not appearing in your `composer.json` file (which may be ok! but then you need to add an entry for Box to know that it needs to include that file as well) or it is but in a way Box currently doesn't understand (in which case a support can be added for it)

**Comment by theofidry** [comment]
Does this answer your question @clevelas?

**Comment by clevelas** [comment]
I think so.  I haven't done config files in composer yet.  I typically just do a require in my main entry script.  I actually have it working with an external config file, which is probably more what I'm looking for anyway.  I did try adding some finder and directories options, but that seemed to break the composer integration.

**Comment by theofidry** [comment]
an easy way to add a directory without breaking the auto-discovery is:

```
{
  "directory": ["config"],
  "force-autodiscovery": true
}
```

Or something like that

**Comment by theofidry** [comment]
The new upgrade should make it easier, cf. https://github.com/humbug/box/pull/360 which I think was a pretty nasty bug
