### ISSUE TITLE
Add pre-(phar) shipping step

### ISSUE THREAD

**Issue by nunomaduro** [humbug/box#350]
A builded application can have access to the Filesystem?

**Comment by theofidry** [comment]
Following up https://github.com/humbug/box/issues/356 (/cc @TomasVotruba), maybe a hook is needed when building the PHAR to for example trigger an app warm-up immediately after the `composer dump-autoload --classmap-authoritative --no-dev` that Box currently does (unless you disabled dumping the autoloader in the settings)

**Comment by theofidry** [comment]
I managed to get it working for Symfony with #378 leveraging the Composer scripts. The extension point may still be necessary at some point, but as long as I can avoid it since it's extremely flimsy, I prefer to do so.

So meanwhile I think this issue can be closed :)
