### ISSUE TITLE
Box excludes Changelog.php from the PHAR

### ISSUE THREAD

**Issue by nicwortel** [humbug/box#351]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.0.0-RC.0, 3.4.0
| PHP version | 7.2.13
| Platform with version | Ubuntu 18.04.1 LTS
| Github Repo | https://github.com/leviy/release-tool

After releasing a new version of our release tool I stumbled upon the following issue. [The build completed without errors](https://travis-ci.com/leviy/release-tool/builds/96442757), but upon running the PHAR it returned the following error:

> PHP Fatal error:  Uncaught Error: Class 'Leviy\ReleaseTool\Changelog\Changelog' not found in phar:///home/nic/projects/leviy/release-tool/build/release-tool.phar/src/Changelog/PullRequestChangelogGenerator.php:33

The build (`release-tool.phar`) can be found here: https://github.com/leviy/release-tool/releases/tag/v1.3.0

After some debugging it turns out that the `Changelog.php` file is excluded from the PHAR because [Box sees all files called `Changelog` or `Changelog.*` as development files and excludes them](https://github.com/humbug/box/blob/4eeb28545646588c3683384e346cb632fc2e7892/src/Configuration.php#L1527).

I understand why this happens, but I was wondering whether it's desirable to exclude such files even if they have a `.php` extension. For now I've fixed the issue by [adding the `src` directly explicitly in our `box.json`](https://github.com/leviy/release-tool/pull/59/files#diff-b3064377dd2b0f0ca4d10133621a777c) (as well as enforcing autodiscovery), so it's not an acute issue anymore, but I wonder if this behavior is desired.

**Comment by theofidry** [comment]
Indeed I don't think they should be excluded if it's PHP files. 

You could have another unorthodox case where you have a `changelog.xml` and you indeed need it, but I think it would be the kind of case where adding the file directly would be enough.

Could you provide a PR for this change?

**Comment by nicwortel** [comment]
@theofidry I'm sorry, this was still on my mental backlog but I never got to it. Thanks for fixing it, though! :+1:
