### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by andrewgorpenko** [humbug/box#353]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.4.0@4eeb285
| PHP version | 7.2
| Platform with version | Windows 10
| Github Repo | - 

Basically, I am unable to use 'compile' command because of this error (command and output below).

_P.S. trying to compile Laravel Lumen application to PHAR (compile ALL files in the src directory)._
 <summary>box.json.dist</summary>
 
 ```json
 {
 "main": "src/public/index.php",
  "directories": [
        "src"
    ],
  "output": "build/client",
  "chmod": "0755",
  "force-autodiscovery": true
 }
 ```

 <summary>Output</summary>
 
 ```bash
 $ php box.phar compile
 > The filename, directory name, or volume label syntax is incorrect.
 ```

**Comment by theofidry** [comment]
Hm that looks really weird, could you try with `--debug` and give the stack trace?

**Comment by andrewgorpenko** [comment]
Result:

```bash
$ php box.phar compile --debug
[debug] Checking BOX_ALLOW_XDEBUG
[debug] The xdebug extension is not loaded
[debug] Process restarting (BOX_ALLOW_XDEBUG=internal||0|*|*)
[debug] Running 'E:\OSPanel\modules\php\PHP-7.2-x64\php.exe' '-n' '-c' 'C:\Users\andre\AppData\Local\Temp\4B70.tmp' 'box.phar' 'compile' '--debug' '--ansi'
The filename, directory name, or volume label syntax is incorrect.
[debug] Restarted process exited 1
```

**Comment by theofidry** [comment]
Oh that's on windows. I have no idea to what extend Box works on it to be honest.

Maybe try the same command with `--no-restart` and I guess `--no-parallel` will be needed as well

**Comment by theofidry** [comment]
>how can I include ALL the directories and files located in src folder, including those that start with ".", line ".git"

If you want to include hidden files I think you will need a custom finder (see the `finders` config entry). However I'm not 100% it's gonna work:

```
// src/Configuration.php

$finder = Finder::create()
            ->files()
            ->filter($blacklistFilter)
            ->filter(
                static function (SplFileInfo $fileInfo) use ($devPackages): bool {
                    foreach ($devPackages as $devPackage) {
                        if ($devPackage === longest_common_base_path([$devPackage, $fileInfo->getRealPath()])) {
                            // File belongs to the dev package
                            return false;
                        }
                    }

                    return true;
                }
            )
            ->ignoreVCS(true)
        ;
```

The `ignoreVCS(true)` can be an issue and I don't know what it does about the dot files (I think it ignores them by default). In which case I think you would need to do a PR to tweak this to allow those 2 settings to be configurable. If `ignoreVCS(true)` is an issue, as ignoring the VCS is already the default, this call could simply be removed allowing you to configure your finder to include VCS files
