### ISSUE TITLE
How to prefix Symfony autodiscovery?

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/box#354]
I worked-around #352 by removing all 3rd party namespaced functions. Now autolaod is working, `vendor/autoload.php` is included inside phar, classes are ok :heavy_check_mark: 

Yet, Symfony autodiscovery seems not to be working:

![image](https://user-images.githubusercontent.com/924196/52170402-ba1bf100-2749-11e9-953b-f91d1d61e566.png)

I think `resource: ../` should be something else with `phar://rector.phar`

```bash
./rector.phar
```

...results in missing service:

![image](https://user-images.githubusercontent.com/924196/52170415-0d8e3f00-274a-11e9-8267-9a7b5427b100.png)

What needs to be done there?

**Comment by TomasVotruba** [comment]
Is there some Symfony  autodiscovery + glob import test case I could inspire from?

**Comment by theofidry** [comment]
>Do you mean this? symfony/symfony@e336ebe
I use this version already, so this is another problem.

I see, good.

>>Fix those cases with a PHP-Scoper patcher.

>How exactly?

The patcher takes any file so it doesn't matter that it's a PHP, XML, Json, or Yaml file. So in your case I think you would need to manipulate the content of the service declaration into something like:

```yaml
services:
    _Prefix\Rector:
        # ...
```

>There is over 30 services.yaml files in variously nested locations.

I understand, best would be IMO to figure a way to deal with this in PHP-Scoper. Sorry I said [PHP-Scoper native patchers](https://github.com/humbug/php-scoper/tree/master/src/Patcher) but I actually meant the [Symfony scopers](https://github.com/humbug/php-scoper/tree/master/src/Scoper/Symfony) (to see how they work I recommend to check [the tests](https://github.com/humbug/php-scoper/blob/master/tests/Scoper/Symfony/YamlScoperTest.php) which I hope are self-explanatory). I think we are just missing a case there to cover your need

**Comment by theofidry** [comment]
>Pure magic. There should be some warning on build at least.

What kind of warning are you thinking about though? It's a pure Symfony error so I guess it should be handled there right?

**Comment by TomasVotruba** [comment]
Personally, I'd throw an exception, untill this gets resolved (if anytime). That would same me 2 hours of my life.

**Comment by theofidry** [comment]
I guess no one had encountered that issue before in Symfony :)

**Comment by TomasVotruba** [comment]
Well, I think I encoutered this few months ago, but I was very frustrated to start such a deep investigation. If you know the solution, it should be reported by the tool.

**Comment by theofidry** [comment]
I don't think there is any way for Box to know about that issue :/ It should be addressed directly in Symfony IMO

**Comment by TomasVotruba** [comment]
I have no idea how PHAR nor box works, so I can't report it.

There might be validation that would check for `resource: ..` that is not followed by a directory in `#*.(yml|yaml)^#` files.

**Comment by theofidry** [comment]
>I have no idea how PHAR nor box works, so I can't report it.

PHAR is just an PHP executable ZIP. All the specifics are due to the implementation but that's the idea. 

>There might be validation that would check for resource: .. that is not followed by a directory in #*.(yml|yaml)^# files.

But it works right? The patch you are mentioning is relying on it no? I thought it was just that the path you gave is incorrect or is it that the path changes from the PHAR to the app?

**Comment by theofidry** [comment]
I my have mixed threads or got confused across the multiple issues: see my comment on it: https://github.com/humbug/box/issues/356#issuecomment-460080776

**Comment by TomasVotruba** [comment]
The initial issue is solved. The exception/validation would be nice to have.
I got list of more WTFs to add to help other using it on Symfony/Nette projects.
