### ISSUE TITLE
How to make phar writable for better debugging?

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/box#356]
At the moment I have to apply trial-error edit of original code, then compile and wait to see the result. It takes lot of time and performance #355 

If I could edit PHAR, I could get instant feedback if any spot is problematic.

How to do that?

**Comment by theofidry** [comment]
There is no easy way since what you are asking is like how to edit a `zip` file directly.

That said I face the same issue several times so here are what I've done so far:

- There is a `--debug` option with box which is strictly equivalent to doing `new Phar('rector.phar')->extractTo('myDir', null, true)`. See [this code](https://github.com/humbug/box/blob/master/src/Console/Command/Compile.php#L252). It allows you to play with the full PHAR content (albeit _outside_ of the PHAR format). Whilst it doesn't solve all issues, it helps out to pinpoint if the issue comes from the code itself our from having the code bundled in the PHAR

When having to deal with PHP-Scoper:

-

**Comment by TomasVotruba** [comment]
> There is a --debug ...

I've tried this as you've suggested before, but it takes the almost same amount of time (1,5-2 mins) to generate, so it's usless for debugging.

The rest seems good for debugging prefixer by file, but I think the issues I've got are related to in-phar content (magic paths mostly).

---

I've read about some `phar.readonly` option. I assumed by name it could be used to write into phar files. What is it for then?

**Comment by theofidry** [comment]
Out of curiosity, how come the Symfony DI is kicking in only in the PHAR? Maybe a hook could be added for the warm-up to not occur within the PHAR.

>I've read about some phar.readonly option. I assumed by name it could be used to write into phar files. What is it for then?

Yes, if you debug PHARs I recommend to put `phar.readonly=0` in your `php.ini` otherwise it's a bit annoying if you wanna manipulate the PHARs directly. Box take care of it but it's really when building the PHAR to not annoy the end user, but for you to dev/debug it's likely necessary

**Comment by TomasVotruba** [comment]
> Out of curiosity, how come the Symfony DI is kicking in only in the PHAR? Maybe a hook could be added for the warm-up to not occur within the PHAR.

I'd like to tell you, but I have no idea. My work with box and phar is purely random, since there is only feedback I get is new error of something missing.

> Yes, if you debug PHARs I recommend to put phar.readonly=0 in your php.ini otherwise it's a bit annoying if you wanna manipulate the PHARs directly. Box take care of it but it's really when building the PHAR to not annoy the end user, but for you to dev/debug it's likely necessary

I'll check my php.ini then.

**Comment by theofidry** [comment]
>I'd like to tell you, but I have no idea. My work with box and phar is purely random, since there is only feedback I get is new error of something missing.

Hm it's a random idea but if you do the `--debug` or extract the built PHAR in a directory, you should b e able to check wether the Container has been warmed up or not. Maybe even the Compiler shouldn't be able to try to be dumped when in a PHAR?

**Comment by TomasVotruba** [comment]
I mean the combination of those elements. I found out the box works well for PHP only packages. Probably because most of phar packages in history used PHP without DI container.

But when you add glob, Nette framework, Symfony framework, phar paths instead of relative ones (e.g `resource: '../'` vs `resource: '../../src'`), many unclear problems shows up.

**Comment by theofidry** [comment]
>But when you add glob, Nette framework, Symfony framework, phar paths instead of relative ones (e.g resource: '../' vs resource: '../../src'), many unclear problems shows up.

I would like to make it better but I think it would be very hard to have 1. a robust solution 2. that would be performant (let's face it: building a PHAR is already super slow we don't want to make it any slower).

However maybe a doc entry on the subject to encourage to double check those paths would be welcome.

On a personal note, I always found those relative paths tricky in Symfony and prefix them with the project path `'%kernel.project_dir%/...` to have absolute paths instead. Then if there is anything to fix I only have `Kernel::getProjectDir()` to take care of

**Comment by TomasVotruba** [comment]
> I would like to make it better but I think it would be very hard to have 1. a robust solution 2. that would be performant (let's face it: building a PHAR is already super slow we don't want to make it any slower).

For these reasons I put these weird stuff to `validate` command.

> However maybe a doc entry on the subject to encourage to double check those paths would be welcome.

I would not expect this little detailed to be sought in README. Embody knowledge :+1: 

> On a personal note, I always found those relative paths tricky in Symfony and prefix them with the project path '%kernel.project_dir%/... to have absolute paths instead. Then if there is anything to fix I only have Kernel::getProjectDir() to take care of

I might give it a try after I fix the Nette issue.

**Comment by theofidry** [comment]
Regarding the specificities of shipping a Symfony app into a PHAR, I wrote up some elements [here](https://github.com/humbug/box/pull/378/files#diff-86bb1eba51dec9a5cef01fd24690d16a), bottom line is you can absolutely not afford the cache to not be warmed up before shipping the PHAR and the bundled code must be in production mode.

For debugging the PHAR itself, you can actually put breakpoints in it. I also plan to add an extract command (see #390) in case you don't want to bother recompiling again with the `--debug` option.

With this, it should already remove a lot of the gotchas :)
