### ISSUE TITLE
Add support for hash_file  Checksum for output file

### ISSUE THREAD

**Issue by benemohamed** [humbug/box#431]
##  Feature Request

Generate a hash value of a `output file`   
Add hash value to costum file with ALGO name 

example:
```json
...
....
....
"output": "dist/test.phar",
"algorithm" : "sha256"
...
...
...
```

Expected in `dist folder` : 

```
.
└── test.phar
└── test.phar.sha256sum
```

**Comment by theofidry** [comment]
What would be the purpose of that file?

Just in case, you can get the hash easily by running `box info foo.phar`

**Comment by benemohamed** [comment]
to verify and to compare it to the one found in the test.phar.sha256sum with the test.phar
Exmple:
```bash
$ sha256sum -b test.phar > test.phar.sha256sum

$ sha256sum --ignore-missing -c test.phar.sha256sum
test.phar: OK

```
but in box if you change the `test.phar` we can't run test.phar
```bash
$ php test.phar
PHP Fatal error:  Uncaught PharException: phar "/test.phar" has a broken signature in
Stack trace:
#0 /test.phar(27): Phar::mapPhar('test.phar')
#1 {main}
  thrown in /test.phar on line 27
```
also sha256sum
```
$ sha256sum --ignore-missing -c test.phar.sha256sum
test.phar: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
sha256sum: test.phar.sha256sum: no file was verified

```
that good to know

**Comment by theofidry** [comment]
I'm a bit confused, what is the point of checking the signature if, when the signature unexpectedly changed, the PHAR cannot be executed in the first place?

The only benefit I could see is if you don't trust the PHAR in the first place and want to check its signature to make sure it has not been corrupted (if you check so by attempting to run the PHAR you may execute malicious code container within it).

However is a question of where do you get the PHAR from: you will have to download the signature from somewhere and if you can do so you can as well download the PHAR directly. Unless the signature is downloadable from a trustable third-party and independent from the PHAR download source, this will not provide any additional safety.

**Comment by benemohamed** [comment]
good point we don't need Checksum with `box`

**Comment by theofidry** [comment]
Note regarding the distribution:

- If you cannot ensure the PHAR is coming from a safe place, either you execute it in a securely isolated environment or you download it again but from a trusted source (and always in HTTPS which includes a checksum check).
- With PHIVE one can GPG sign the PHAR and register the GPG key on phar.io, which can do a check (and the check is more reliable since the key is from a secure third-party source)

**Comment by theofidry** [comment]
Will be closing this issue then :)
