### ISSUE TITLE
__autoload() is deprecated, use spl_autoload_register() instead

### ISSUE THREAD

**Issue by maks-rafalko** [humbug/box#439]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.8.0@e7d8df3 2019-06-08 14:25:00 UTC
| PHP version | PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1
| Platform with version | Ubuntu
| Github Repo | infection/infection

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "output": "build/infection.phar",

    "git-version": "package_version",

    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Json",
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\PhpScoper"
    ],
    "files": ["resources/schema.json"]
}
 ```
</details>

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
<?php

return [
    'whitelist' => [
        "Safe\\*"
    ],
];
 ```

</details>

When the phar is compiled and executed, the following deprecation warnings are displayed:

```bash
PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in phar:///infection/build/infection.phar/vendor/autoload.php on line 78

Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in phar:///infection/build/infection.phar/vendor/autoload.php on line 78
You are running Infection with PCOV enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...
```

This issue is not reproduced without `scoper.inc.php`

Related to https://github.com/infection/infection/issues/795

**Comment by sanmai** [comment]
This is the issue: https://github.com/justinrainbow/json-schema/issues/574

The problem goes away should one replace `__autoload` with `spl_autoload_register` in `bin/validate-json`

**Comment by sanmai** [comment]
https://github.com/justinrainbow/json-schema/pull/589 should fix the problem
