### ISSUE TITLE
Builds are failing (PHP 7.4)

### ISSUE THREAD

**Issue by jakzal** [humbug/box#446]
I was trying to build on PHP 7.4 and noticed failures are not PHP version related.

i.e. https://travis-ci.org/humbug/box/jobs/611311228

<img width="702" alt="image" src="https://user-images.githubusercontent.com/190447/70433857-ada7a980-1a7a-11ea-87ac-4b71dee412f2.png">

Also, on my machine I get some additional debugging information as a result of #444. The `test_it_can_build_a_PHAR_file_in_debug_mode` test fails because of this with an unclear error:

```
1) KevinGH\Box\Console\Command\CompileTest::test_it_can_build_a_PHAR_file_in_debug_mode
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Exception: Serialization of 'class@anonymous' is not allowed in Standard input code:357
Stack trace:
#0 Standard input code(357): serialize(Array)
#1 Standard input code(683): __phpunit_run_isolated_test()
#2 {main}
  thrown in Standard input code on line 357
```

**Comment by theofidry** [comment]
The real error can be checked by removing `@runTestsInSeperateProcess` and running that test only with `--filter`. PHPUnit doesn't display more information and only that obscure error because the underlying exception/error is not serializable hence cannot be passed to the main process to be displayed

**Comment by theofidry** [comment]
Also probably related: https://github.com/humbug/php-scoper/issues/357

**Comment by jakzal** [comment]
To clarify: builds are failing on all PHP versions at the moment.

**Comment by theofidry** [comment]
Hm ok, will try to take a look this week

**Comment by jakzal** [comment]
The actual failure:

```
There was 1 failure:

1) KevinGH\Box\Console\Command\CompileTest::test_it_can_build_a_PHAR_file_in_debug_mode
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'[debug] Current memory limit: "512MB"
+'[debug] Changed the memory limit from "128MB" to "512M"
 [debug] Checking BOX_ALLOW_XDEBUG
-[debug] The xdebug extension is not loaded
+[debug] The Xdebug extension is not loaded
 [debug] Disabled parallel processing

     ____

/Users/kuba/Projects/box/tests/Console/Command/CompileTest.php:1136
```

That's why I think it's related to #444. Strangely that build has passed...

**Comment by theofidry** [comment]
Hm indeed, can also be related to either xdebug itself or the composer/xdebug-handler package

**Comment by jakzal** [comment]
It's inconsistent between PHP versions. We shouldn't rely on output this much imo.

If I fix PHPUnit tests run directly on travis, there's some failing on docker (i think).

I think the test suite could do a lot with making it portable.

**Comment by theofidry** [comment]
Indeed might be worth to pin those on a specific version via docker.

I don't want to rely too much on this input, but since it's essential logs I also want to make sure those messages are displayed correctly...

**Comment by jakzal** [comment]
Well, in my view we should never assert the whole output, but rather look for specific parts. I.e. 

* debug messages are displayed
* memory usage has was bumped
* etc

these are separate test.

**Comment by theofidry** [comment]
but if you do that you are missing _where_ those are displayed, which has its importance...

**Comment by jakzal** [comment]
if order is important you encode it in a test.

**Comment by jakzal** [comment]
This is required for box to actually work on PHP 7.4: https://github.com/opis/closure/pull/42
