### ISSUE TITLE
Projects to check out

### ISSUE THREAD

**Issue by theofidry** [humbug/box#45]
- https://github.com/Elendev/ElendevPhar
- https://github.com/IcecaveStudios/near
- https://github.com/JeroenDeDauw/PharBuilder
- https://github.com/MacFJA/PharBuilder
- https://github.com/Modularr/Phar
- https://github.com/brad-jones/pharbuilder
- https://github.com/clue/phar-composer
- https://github.com/cmpayments/crate
- https://github.com/crodas/Phar-Builder
- https://github.com/index0h/yii2-phar
- https://github.com/keradus/PharBuilder
- https://github.com/kos33rd/pharaon
- https://github.com/laravel-zero/framework
- https://github.com/mauris/concrete
- https://github.com/mvccore/packager
- https://github.com/oleics/php-ac-build-phar
- https://github.com/parcel-bundler/parcel
- https://github.com/theseer/Autoload

Edit: some elements of the list are coming from https://github.com/MacFJA/PharBuilder/issues/15

**Comment by keradus** [comment]
wow, I'm on the list :D 
from 2014 :smiling_imp:
