### ISSUE TITLE
🤝🏻 Interest in taking the Box Project organization?

### ISSUE THREAD

**Issue by kherge** [humbug/box#453]
Hi @theofidry, any interest in taking over the [Box Project organization](https://github.com/box-project)?

**Comment by theofidry** [comment]
Hi Kevin!

Thanks a lot for the proposition! That would be great although to be
completely honest I’m also unsure of what I should do with it.

At the start I wanted to migrate humbug/box back to box, but now I feel
more conflicted about it as it is very likely to result in a lot of work:

- rename the box2 repository to just “box”
- release a v4
- help with the tools that already migrated t box3 (it includes a couple of
projects that I maintain)
- likely will result in the loss of the v3 GitGub releases

So whilst it could be done, I feel it would be more practical to point box2
to box and archive the project instead.

I would however prefer to be clear on that with you as I feel just
accepting your offer and doing so right afterwards would be quite a jerk
move.

Obviously I can totally understand that you are not happy with that idea: I
had to do a similar move with humbug/humbug ans infection/infection so I
can completely sympathise with the situation.

So if you are ok with that then yes. No hard feeling whatever your decision
is I know it’s not an easy one :)

**Comment by kherge** [comment]
I will support whatever you and the community decide. I have some ideas as well, but if there are any disagreements I will defer to your judgement. I will add you to the organization as an admin and you can remove me if you prefer.

1. Move Box 3 to the organization, but preserve the Composer package name, `humbug/box`. GitHub will automatically redirect, but I think the repository URL on the Packagist website will need to be updated (not sure how your CI/CD pipeline is affected). From the user side of things, they shouldn't notice a thing and their dependency on `humbug/box` should continue to work as expected.
2. With the exception of Box 3 (of course), all of the repositories in the organization should be archived and marked as abandoned in Packagist, wiping the slate clean. There is already a mixture of abandoned dependencies and they have not seen active development in years. If there are any active users of those repositories, they can fork the archived repositories.

**Comment by kherge** [comment]
Issue resolved. 😁

**Comment by rask** [comment]
So the org is switching hands I presume?

**Comment by theofidry** [comment]
I guess, but I've returned only yesterday so I got a lot of to catch up with 😅

**Comment by rask** [comment]
Okay, thanks for the info. :)

**Comment by theofidry** [comment]
Sorry it took so long, I couldn't do it straight away due to humbug/box being a fork so I had to go through GitHub support... but done now :)
