### ISSUE TITLE
Add Brotli as a compression option

### ISSUE THREAD

**Issue by peterjaap** [humbug/box#455]
We've had great results using [Brotli](https://github.com/google/brotli) as a compressing algorithm instead of GZ. It would be great to offer it as a non-default compression option to box.

Of course, the host running the phar would need [php-ext-brotli](https://github.com/kjdev/php-ext-brotli) to be able to run the phar.

**Comment by theofidry** [comment]
Have you checked if, once you installed the extension, you can compress a `PHAR` with it? I can't see any reference to the PHAR API in the extension so I'm wondering if that will work

**Comment by peterjaap** [comment]
@theofidry ah, I didn't know it had to have a specific PHAR API in the extension to have it work. Closing.
