### ISSUE TITLE
Why hidden files like .env excluded from box if it specified via finder section?

### ISSUE THREAD

**Issue by hanovruslan** [humbug/box#458]
Hi there! Thanks a lot for such useful composer package!

Question:
Why hidden files like .env excluded from box if it specified via finder section?
```json
    "finder": [
        {
            "in": ".",
            "name": ".env"
        },
    ],
```

The purpose is to optionally include .env into box if it defined for applications that can be executed with and without .env file

**Comment by theofidry** [comment]
I suppose because behind it is using the Symfony Finder component and is configured to ignore dot files and directories.

I think it's a case where using `files` or `directories` is more appropriate

**Comment by hanovruslan** [comment]
Just have checked additional finder options - yes, you are correct!
Thanks again!
