### ISSUE TITLE
Autoload files issue

### ISSUE THREAD

**Issue by veewee** [humbug/box#462]
Hello,

I got following issue with the dump-autoload part of the project.

Imagine a project that depends on amp. In that case the `autoload_files.php` will look like this:

```php
# vendor/composer/autoload_files.php 

return array(
    'e8aa6e4b5a1db2f56ae794f1505391a8' => $vendorDir . '/amphp/amp/lib/functions.php',
);
```

Next I build a Phar:

* The php-scoper prefixes the file with a unique namespace.
* A bit later, the dump-autoload feature kicks in. This writes out the same autoload hash, even though it is a different file. See composer snippet underneath:

See : https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L1111-L1114
```php
    protected function getFileIdentifier(PackageInterface $package, $path)
    {
        return md5($package->getName() . ':' . $path);
    }
```

Now my codebase contains a part that tries to load the composer files from the project you are working on and next includes the composer file inside the phar.

In a project which does not have amp installed, it works as expected.
In a project which also has amp installed, it results in this error:

```
Error: Call to undefined function _HumbugBoxb93c28c1c6c6\Amp\Promise\wait() in phar:///
```

This is a logical issue, since the has is the same and the composer autoloader looks like this:

```php
function composerRequire06055fcc914a6ce5ad6e16c76fe19a27($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
```

This is why it won't load twice and it only loads the regular Amp wait function.

To solve the issue, I tried:

* Changing the file with a scoper patcher : no luck -> the composer autoload is overwritten afterwards
* Creating hacky code in a custom stub - which is still a bit buggy.
* Looking inside the codebase of box to see if there is something else I can hook into.

None of the above really worked.
Any suggestions on how I could change the phar generation so that both files are included?

Thanks!

**Comment by theofidry** [comment]
It is indeed a known issue see https://github.com/humbug/php-scoper/issues/298. I'll close this one as it's better being tracked there. There is no clear solution yet, but any idea/input would be appreciated

**Comment by veewee** [comment]
Thanks!
