### ISSUE TITLE
Configuration::runGitCommand() should respect base-dir

### ISSUE THREAD

**Issue by discordier** [humbug/box#465]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.8.4
| PHP version | all
| Platform with version | all

I have the following setup:
1. we create the `box.json` dynamically in CI in `/tmp/<unique build directory>` - eg. `/tmp/build-5eeee25/box.json`
2. We build in working directory of code eg. `/build/project-0`

We also want to include the commit hash as placeholder, hovever, Box does run the git commands in the directory of the config instead of running them in the configured `base-dir`.

I am willing to provide a PR but am unsure of how to approach this issue.
IMO it should be implemented here:
https://github.com/humbug/box/blob/6a148c68279a4f0b679b1f2c7e5068b27a7048ec/src/Configuration/Configuration.php#L2719
Currently I am thinking of something like this:
 ```diff
-    private static function runGitCommand(string $command, string $file) : string
+    private static function runGitCommand(string $command, string $path): string
     {
-        $path = dirname($file);
```
Additionally, the path will be added as additional parameter to the  `Configuration::retrieveReplacements()` and all `Configuration::retrieveGit*()` handlers instead of the file.
The value of the path will get determined in `Configuration::create()` as `base-dir` > `dirname($file)` > `getcwd()`.

Does anyone see a problem with this approach?
Am I on the right track that the priorities should be:
1. configured `base-dir` in config
2. base dir of config file.
3. cwd of process

<details>
 <summary>generated `/tmp/build-5eeee25/box.json`</summary>

  ```json
{
    "algorithm": "SHA512",
    "alias": "phpcq",
    "banner": "This file is part of some project",
    "check-requirements": false,
    "compactors": [
        "KevinGH\\\\Box\\\\Compactor\\\\Php",
        "KevinGH\\\\Box\\\\Compactor\\\\PhpScoper",
        "KevinGH\\\\Box\\\\Compactor\\\\Json"
    ],
    "compression": "GZ",
    "datetime": "release-date",
    "git-version": "git-version",
    "base-path": "/build/project-0"
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ command
 > output
    ____
    / __ )____  _  __
    / __  / __ \| |/_/
    / /_/ / /_/ />  <
    /_____/\____/_/|_|
    
    
    Box version 3.8.4@120b0a3 2019-12-13 17:22:43 UTC
    
    // Loading the configuration file
    // "/tmp/build-5eeee25/box.json".
    
    
    In Configuration.php line 1153:
    
    The tag or commit hash could not be retrieved from "/tmp/build-5eeee25": The tag or commit hash could not be retrieved from "/tmp/build-5eeee25": fatal: not a git repository (or any of the parent directories): .git
    
    
    In Configuration.php line 1351:
    
    The tag or commit hash could not be retrieved from "/tmp/build-5eeee25": fatal: not a git repository (or any of the parent directories): .git
    
    
    compile [-c|--config CONFIG] [--debug] [--no-parallel] [--no-restart] [--dev] [--no-config] [--with-docker] [-d|--working-dir WORKING-DIR]
 ```
</details>

**Comment by theofidry** [comment]
The approach looks good to me, it indeed makes a lot more sense 👍

**Comment by discordier** [comment]
See #466 - However, tests are failing miserably but appear to be unrelated to my changes.
