### ISSUE TITLE
Whitelist in scoper is probably not applied on closure files

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/box#470]
Hi Theo, 

thanks for making box better and better. It helps me deploy Rector very effectively :+1: 

<br>

I migreated Symfony YAML files to PHP configs. This worked before in YAML files, but not in PHP file with closure.

I have a scoper.php.inc:

```php
return [
    // ...
    'whitelist' => ['Symfony\Component\Console\Style\SymfonyStyle'],
]
```

<br>

In YAML the class was skipped :+1: 

```yaml
# config.yaml
services:
    Symfony\Component\Console\Style\SymfonyStyle: null
```

But in `config.php` it gets prefixed:

```php
# config.php
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator) : void {
    $services = $containerConfigurator->services();
    $services->set(\_HumbugBoxc5a1b533f50a\Symfony\Component\Console\Style\SymfonyStyle::class);

    # should be
    # $services->set(Symfony\Component\Console\Style\SymfonyStyle::class);
};
```

The `config.php` file only contains static closure, not a clas as mot of other file. So it might be the cause.

<br>

Is there anything you need from me to improve the broken part detection?

**Comment by theofidry** [comment]
I'm actually surprised it didn't get scoped it the YAML, should it be scoped in both cases and an alias be added to `SymfonyStyle`? Maybe there was a patcher registered?

A more detailed explanation on how the whitelisting is done in PHP-Scoper is available [here](https://github.com/humbug/php-scoper/#class-whitelisting). I know it's a bit confusing, but the approach of leaving whitelisted code alone was too fragile hence the choice of leveraging aliases

**Comment by TomasVotruba** [comment]
> I'm actually surprised it didn't get scoped it the YAML, should it be scoped in both cases and an alias be added to SymfonyStyle? Maybe there was a patcher registered?

I recall there was somethign weird with aliases, now it makes.

Ah, that's maybe why. So I have to unscope it manually.

**Comment by TomasVotruba** [comment]
I managed to fix this by un-preffixing classses manually:
https://github.com/rectorphp/rector/pull/3736/files#diff-463a36e4a5687fb2366b5ee56cdad92dR92-R98
