### ISSUE TITLE
Add single threaded mode

### ISSUE THREAD

**Issue by theofidry** [humbug/box#53]
To speed up things we are leveraging Amp to process the files in parallel. This is however very inconvenient for debugging as it's no longer possible to put a break point in the code executed in parallel.

@kelunik is there anything on Amp side for this? Otherwise I was thinking of replacing the parallel processing by a plain array_map...

**Comment by kelunik** [comment]
@theofidry There isn't anything currently. I guess we could modify `parallel-functions` and respect an environment variable or something like that to use `array_map` instead of a parallel mapping.

**Comment by theofidry** [comment]
I'll do a PR on parallel-functions for it then :)

**Comment by theofidry** [comment]
Closed by #80. Maybe this can be simplified if https://github.com/amphp/parallel-functions/pull/8 is merged
