### ISSUE TITLE
Breaks entire composer installation due to bad autoload rules

### ISSUE THREAD

**Issue by weirdan** [humbug/box#84]
Happening: since 3995ac0de95cc86c523571fb509e775625df112a

Steps to reproduce:
```
composer global require 'humbug/php-scoper:^1.0@dev'
composer global require humbug/box:dev-master
```
After this composer global commands (even unrelated, like `show -i`) will fail with `failed opening required(/home/weirdan/.composer/vendor/composer/../humbug/box/vendor/humbug/php-scoper/src/functions.php)`

When box is installed globally (or as a dependency of some other project) it doesn't have `vendor` subfolder. It's dependencies are in sibling folders instead.

Suggested fix: put that file in `autoload/files` section of php-scoper, remove here.

**Comment by theofidry** [comment]
Huh I see. Sorry about that I'll fix that in a sec
